# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8bd76d550cc49c07e19d7aec9e4d258a71f6a07e5e1a6596deb07bf0a848948b9d4cb4dc26560c35e16cc3c974508c4717ec018e3bb8463d2c8469bec383b53

test:
  secret_key_base: 8fc25a9d73f3067e1bbb643c2ca19af332114864ce07a5705c3cf775b92a4aadfae42d4cb419b6a1b3b56479f529dd60b6f9a126ded938186aaf01ace4e43b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
